[package]
name = "get_lyric"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
color-eyre = "0.6.3"
ego-tree = "0.9.0"
reqwest = "0.12.9"
scraper = "0.21.0"
tokio = { version = "1.41.1", default-features = false, features = ["macros", "rt-multi-thread"] }
